language: haskell

sudo: false
cache:
  directories:
  - $HOME/.stack/

before_install:
- mkdir -p ~/.local/bin
- export PATH=~/.local/bin:/opt/ghc/7.10.2/bin:$PATH
- ghc --version
- travis_retry curl -L https://github.com/commercialhaskell/stack/releases/download/v0.1.1.0/stack-0.1.1.0-x86_64-linux.gz | gunzip > ~/.local/bin/stack
- chmod a+x ~/.local/bin/stack

addons:
  apt:
    sources:
    - hvr-ghc
    packages:
    - ghc-7.10.2

install:
  - stack setup --no-terminal
  - stack build --only-snapshot --no-terminal

script:
  - stack build --no-terminal
